# Generated by Django 4.1.3 on 2022-11-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoItem',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('body', models.CharField(max_length=100)),
                ('date_created', models.DateField(auto_now=True)),
                ('date_done', models.DateTimeField()),
            ],
        ),
    ]
